### PR TITLE
fix: improved performance of estimateAll method

### PR DESCRIPTION
**Pull request by melianessa**
Improve performance (x2) of the `estimateAll` method by awaiting `estimateSubmissionFee` and `estimateMaxFeePerGas` in a batch after `estimateRetryableTicketGasLimit`. 
Before:
image
image
image

After:
image
image
image

### CODE REVIEW

**Comment by melianessa** [comment]
Signed 🙂

**Comment by hkalodner** [comment]
@cla-bot check

**Comment by spsjvc** [comment]
Hey @melianessa, thank you very much for contributing! Could you update your fork with the latest changes from `main`, as those should fix the issues with CI your PR had. 🙂

**Comment by spsjvc** [comment]
> Hey @melianessa, thank you very much for contributing! Could you update your fork with the latest changes from `main`, as those should fix the issues with CI your PR had. slightly_smiling_face

@melianessa I think this will fix the final issue with permissions in the Lint job: https://github.com/OffchainLabs/arbitrum-sdk/pull/252

Could you update your PR once again? :slightly_smiling_face:

**Comment by melianessa** [comment]
> > Hey @melianessa, thank you very much for contributing! Could you update your fork with the latest changes from `main`, as those should fix the issues with CI your PR had. slightly_smiling_face
> 
> @melianessa I think this will fix the final issue with permissions in the Lint job: #252
> 
> Could you update your PR once again? 🙂

Done 🙂

**Comment by mindrunner** [comment]
@spsjvc any reason for this not being merged yet?

**Review by fionnachan — APPROVED** [review]

**Comment by spsjvc** [comment]
Hey @melianessa! Due to some issues with CI permissions for external contributors, we've copied your changes to another PR that we've now merged: https://github.com/OffchainLabs/arbitrum-sdk/pull/288.

We appreciate the contribution and will work on fixing this so it's easier for more people to contribute to the project. 💙

**Pull request closed without merging**
